export const FETCH_POSTS = 'FETCH_POSTS';
export const CHANGE_POSITION = 'CHANGE_POSITION';
export const DRILL_CO_ORD = 'DRILL_CO_ORD';
export const DIRECTORATE_DATA = 'DIRECTORATE_DATA';
export const DIRECTORATE_ALL_DATA = 'DIRECTORATE_ALL_DATA';


